### ISSUE TITLE
Escape after blur should dismiss modal

### ISSUE THREAD

**Issue by chantastic** [instructure/ic-modal#1]
I soooo don't mean to be a pain in the ass; if I were smarter I'd make a PR.

---

It would be nice if pressing escape, after bluring an input, closed the modal:
- [x] Escape with modal focused closes modal
- [x] Escape with input focused blurs input
- [ ] Escape, after input is blurred, closes modal

**Comment by ryanflorence** [comment]
No such thing as a pita when finding issues :)

I don't know exactly what "Escape, after input is blurred, closes modal" means.

I just did this:
1. opened the modal
2. focused a text field
3. clicked away from the text field, but still in the modal
4. hit escape
5. the modal closed

Can you break down the scenario you're talking about? or maybe record a little screencast?

**Comment by chantastic** [comment]
In our sites, we found that users (that used `esc` to close modals) expected the modal to "always eventually" be closed with `esc`.

This case came up a lot:
1. Open modal
2. Focus (or get auto-focused) on an input
3. Escape (first), to blur the input
4. Escape (second), to close the modal

Here's a video.

![ic-modal_esc](https://cloud.githubusercontent.com/assets/658360/2689857/3fb56ad0-c322-11e3-8e58-6d16a009df3f.gif)

For us, this issue may be exacerbated because we auto-focus `:input:enabled:visible:first`.

**Comment by ryanflorence** [comment]
How do you get escape to blur an `<input type="text">`? I can't get my browser to do that.

If I focus the input outside of the modals, esc does nothing (doesn't blur).

When I hit esc with an active input it just closes the modal.

If I do esc in the select box it blurs, and then esc again closes the modal.

If I could reproduce this I'd absolutely fix it.

**Comment by chantastic** [comment]
Frick!

So sorry to have wasted your time on this, Ryan.

This is on me.  I had to reinstall all my Chrome plugins and Vimium didn't have my normal exclude-list.

For shame.
