### ISSUE TITLE
Trigger one modal dialog inside other modal dialog

### ISSUE THREAD

**Issue by lessless** [instructure/ic-modal#22]
Imagine that as user I opened a registration modal dialog and then I want to switch to the login modal dialog.
Now {{#ic-modal-trigger}} inside modal dialog just close opened dialog and do not open desired.

**Comment by ryanflorence** [comment]
You should close the first, open the a new one, and the open the old one again if you want.

It makes no sense to have two open modals at the same time.

**Comment by lessless** [comment]
I do not mean that there should be opened two modal windows. What I wanted to say that the 'close-open' flow can be managed by the  {{#ic-modal-trigger}}.
Or content can be just swapped.
